<template>

<section class="pt-3">
<div class="w-full lg:w-4/12 px-4 mx-auto">
  <div class="relative flex flex-col min-w-0 break-words bg-gray-700 w-full mb-6 shadow-xl rounded-lg mt-16">
    <div class="px-6">
      <div class="flex flex-wrap justify-center">
        <div class="w-full px-4 flex justify-center">
          <div class="relative w-40 h-40 rounded-full">
            <img alt="..." src="/src/assets/howl.png" class="align-middle rounded-full pt-7">
          </div>
        </div>
      </div>
      <div class="text-center mt-6 pb-6">
        <h3 class="text-xl font-semibold leading-normal mb-2 text-gray-50 mb-2">
          Jenna Stones
        </h3>
        <div class="flex justify-between mb-2 text-gray-100 mt-5">
            <p>Joined date</p><p>12/7/2000</p>
          
        </div>
        <div class="flex justify-between mb-2 text-gray-100 mt-5">
            <p>Bookedmarked</p><p>50</p>
          
        </div>
      </div>
    </div>
  </div>
</div>
</section>

</template>